name: traccar_manager
description: "Traccar Manager"
publish_to: 'none'
version: 5.2.0+63

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^7.0.0
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.6.0
  local_auth: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  rate_my_app: ^2.3.2
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.15
  url_launcher: ^6.3.2
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.10.5
  webview_flutter_wkwebview: ^3.23.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
