name: traccar_manager
description: "Traccar Manager"
publish_to: 'none'
version: 5.1.2+55

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^6.4.0
  firebase_analytics: ^11.5.1
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.8
  firebase_messaging: ^15.2.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  rate_my_app: ^2.3.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.5.0
  webview_flutter_wkwebview: ^3.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
